### ISSUE TITLE
ln(0)

### ISSUE THREAD

**Issue by gtbot2007** [wgxli/complex-function-plotter#31]
ln(0) gives as −36.841+1.571i and I have no idea where this number is coming from or why

**Comment by wgxli** [comment]
This is because internally we compute ln(z + 1e-16 i) to obtain a consistent branch cut when evaluating composed functions. The offset 1e-16 is limited by GLSL resolution on the GPU.
 
Infinity is not expressible in the GLSL representation I am using, so as a compromise I have special-cased ln(0) to -10^100 in the latest update, as well as reducing the epsilon and using it only when needed.
